BEGIN;
SELECT 'Running adding basic skills';

INSERT INTO cyberpunk.skills(skill, attribute, description)
VALUES
('personal grooming', 'ATTR', 'Increases attractiveness of the character and helps with social interactions, e.g. relationships and persuasion' ),
('wardrobe and style', 'ATTR', 'Skill of knowing what to wear. Helps with social interactions, e.g. relationships and persuasions'),
('endurance', 'BODY', 'Ability to withstand pain or hardships for long periods of time (e.g. hunger, sleeplessness, thirst)'),
('strength feat', 'BODY', 'Skill of using your raw physical power for things (e.g. rip phone book, snap handcuffs, bend metal bars..)'),
('swimming', 'BODY', 'Required to know how to swim'),
('interrogation', 'COOL', 'Skill of drawing information out of a subject and forcing his secrets into the open'),
('intimidate', 'COOL', 'Skill of getting people to do what you want by force of personality or physical coercion'),
('oratory', 'COOL', 'Skill of public speaking. Rockers can add +1 to Charismatic leadership if this skill is +6'),
('resist torture/drugs', 'COOL', 'Defence against interrogation and mind controlling drugs on a successful roll'),
('streetwise', 'COOL', 'Knowledge of the streets - where to get illegal and contraband items, how to talk to criminal elements and avoiding bad situations in bad neighbourhoods'),
('human perception', 'EMP', 'Skill of detecting lies, evasions, moods and other emotional clues'),
('interview', 'EMP', 'Skill of eliciting interesting anecdotes from an interview subject. Not used to get specific information, but e.g. to get the subject to make a slip with what they are saying'),
('leadership', 'EMP', 'Skill of convincing people to follow you'),
('seduction', 'EMP', 'Skill of forming and maintaining romantic relationships'),
('social', 'EMP', 'Ability to deal with social situations'),
('persuasion', 'EMP', 'Ability to talk others into doing what you want'),
('perform', 'EMP', 'Skill of trained acting'),
('anthropology', 'INT', 'Knowledge of human cultures, habits and customs'),
('awareness', 'INT', 'Ability to notice things around the character'),
('biology', 'INT', 'General knowledge of animals, plants and other biological systems'),
('botany', 'INT', 'General knowledge of plants and plant identification'),
('chemistry', 'INT', 'Required skill of mixing chemicals and using various compounds'),
('composition', 'INT', 'Required kill of writing songs, articles or stories'),
('diagnose illness', 'INT', 'Skill of clinically diagnosing symptoms and medical problems'),
('education', 'INT', 'Basic education level (e.g. can character read/write, can character do any basic math) and sort of "trivia" skill'),
('expert', 'INT', 'The expertise of some subject'),
('gamble', 'INT', 'Skill of knowing how to make bets, figure odds and play games of chance successfully'),
('geology', 'INT', 'Functional knowledge of rocks, minerals adn geologic structures'),
('hide', 'INT', 'Skill of losing pursuers, covering tracks and evading people'),
('history', 'INT', 'Knowledge of facts and figures of past events'),
('know language', 'INT', 'Ability to speak some language'),
('library search', 'INT', 'Skill of using databases, DataTerms, libraries and other compiled information sources'),
('mathematics', 'INT', 'Skill of understanding calculations, mathematical formulas and overall logic'),
('physics', 'INT', 'Knowledge of physical principles'),
('programming', 'INT', 'Skill of writing programs and re-program computer systems'),
('shadowing', 'INT', 'Skill of shadowing and following people (mostly in urban areas)'),
('stock market', 'INT', 'Ability to play and manipulate the stock market'),
('system knowledge', 'INT', 'Basic knowledge of the Net and the lore and history'),
('teaching', 'INT', 'Skill of imparting knowledge to someone else. Must have higher skill than the student on what is being taught'),
('wilderness survival', 'INT', 'Required skill for knowing how to survive in the wilds (e.g. set traps, forage wood, track game..)'),
('zoology', 'INT', 'Knowledge of lifeforms and their relation to the environment'),
('athletics', 'REF', 'Required skill of accurate throwing, climbing and balancing'),
('brawling', 'REF', 'Skill of street fighting without any martial arts'),
('dance', 'REF', 'Ability to move body rhythmically'),
('dodge/escape', 'REF', 'Skill of dodging melee attacks and escaping grapples'),
('driving', 'REF', 'Skill of piloting ground vehicles'),
('fencing', 'REF', 'mastery of swords, rapiers and monoblades'),
('handgun', 'REF', 'Required skill of effectively use hand guns (including cyberwear types)'),
('heavy weapons', 'REF', 'Required skil of effectively use heavy weapons (e.g. grenade launchers, autocannons, mortars, HMG..)'),
('martial arts', 'REF', 'Skill covers a specific martial art and the ability to use it - these are more effective than brawling'),
('melee', 'REF', 'Ability to use knives, axes, clubs etc. (Including melee cyber weapons)'),
('motorcycle', 'REF', 'Required skill to operate two and three-wheeled motor vehicles'),
('heavy machinery', 'REF', 'Required skill to operate big machines (e.g. tractors, tanks, large trucks..)'),
('piloting', 'REF', 'Required skill to operate flying vehicles'),
('rifle', 'REF', 'Required skill to effectively operate rifles and shotguns'),
('stealth', 'REF', 'Skill of hiding in shadows and moving silently'),
('smg', 'REF', 'Required skill to operate SMGs effectively'),
('aero tech', 'TECH', 'Required skill for repairing fixed wing aircraft'),
('av tech', 'TECH', 'Required skill of repairing ducted fan aerodyne vehicles'),
('basic tech', 'TECH', 'Required skill for building and repairing simple mechanical and electronic devices'),
('cryotank operation', 'TECH', 'Required skill for operating, repairing and maintaining body chilling devices'),
('cyberdeck design', 'TECH', 'Required skill for designing cyberdecks'),
('cybertech', 'TECH', 'Required sill for repairing and maintaining cyberwear'),
('demolitions', 'TECH', 'Technical know-how of explosives'),
('disguise', 'TECH', 'Skill of disguising and resembling someone else'),
('electronics', 'TECH', 'Required skill for repairing and modifying electronic instruments'),
('electronic security', 'TECH', 'Skill of installing or countering electronic eyes, locks, bugs, tracers, security cameras, pressure plates etc.'),
('first aid', 'TECH', 'Skill of binding wounds, stop bleeding and revive a stunned patient'),
('forgery', 'TECH', 'Skill of copying and creating fake documents and their identification'),
('gyro tech', 'TECH', 'Skill of maintaining and repairing of rotorwing aircraft'),
('drawing', 'TECH', 'Skill of producing professional drawings'),
('photography', 'TECH', 'Skill of producing professional photographs or motion pictures'),
('pharmaceuticals', 'TECH', 'Skill of designing and manufactoring of drugs and medicines (chemistry +4 required!)'),
('pick lock', 'TECH', 'Skill of picking locks and breaking into sealed containers or rooms'),
('pick pocket', 'TECH', 'Required skill for picking pockets without being noticed'),
('play instrument', 'TECH', 'Skill of playing a certain musical instrument'),
('weaponsmith', 'TECH', 'Required skill for repairing and maintaining weapons');

COMMIT;