db = 'cyberpunk'
user = 'cyber'
password = 'cyber1'
host = '127.0.0.1'
schema = 'cyberpunk'

table_characters = f'{schema}.characters'
table_character_skills = f'{schema}.character_skills'
table_skills = f'{schema}.skills'
table_combat_session = f'{schema}.combat_session'
table_reputation = f'{schema}.character_reputation'
table_character_armors = f'{schema}.character_armor'
table_character_weapons = f'{schema}.character_weapons'
table_character_sp = f'{schema}.character_sp'