name: Run Pytest

on: [push, pull_request]  # Run tests on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Runs tests on Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Fetches the repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Change this if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest  # Install pytest if not in requirements.txt

      - name: Run tests
        run: pytest
